
export const BuildingCompanies = [
	{
		id: 1,
		company_id: 1,
		title: "Golder House",
		comment: "Продается 2х комнатная квартирав Юнусабадском районе",
		toRailway: "4 мин до метро",
		space: "54.5",
		monthly: "2,000,000",
		address:'Юнусабад, ул. Бунёдкор, 24а дом',
		src: "https://www.ubm-development.com/magazin/wp-content/uploads/2020/03/kl-main-building-d-Kopie.jpg",
	},
	{
		id: 2,
		company_id: 2,
		title: "Namuna",
		comment: "Продается 2х комнатная квартирав Юнусабадском районе",
		toRailway: "4 мин до метро",
		space: "54.5",
		monthly: "3,400,000",
		address:'Юнусабад, ул. Бунёдкор, 24а дом',
		src: "https://images.adsttc.com/media/images/6286/ac71/03d0/a701/6541/0bf1/newsletter/yellow-foot-residential-building-oa-lab_6.jpg?1652993321",
	},
	{
		id: 3,
		company_id: 3,
		title: "Golder House",
		comment: "Продается 2х комнатная квартирав Юнусабадском районе",
		toRailway: "4 мин до метро",
		space: "54.5",
		monthly: "2,000,000",
		address:'Юнусабад, ул. Бунёдкор, 24а дом',
		src: "https://i.ytimg.com/vi/o4clqyDFeAY/maxresdefault.jpg",
	},

	{
		id: 4,
		company_id: 4,
		title: "Golder House",
		comment: "Продается 2х комнатная квартирав Юнусабадском районе",
		toRailway: "4 мин до метро",
		space: "54.5",
		monthly: "2,000,000",
		address:'Юнусабад, ул. Бунёдкор, 24а дом',
		src: "https://images.adsttc.com/media/images/6286/ac71/03d0/a701/6541/0bf1/newsletter/yellow-foot-residential-building-oa-lab_6.jpg?1652993321",
	},
	{
		id: 5,
		company_id: 5,
		title: "Namuna",
		comment: "Продается 2х комнатная квартирав Юнусабадском районе",
		toRailway: "4 мин до метро",
		space: "54.5",
		monthly: "3,400,000",
		address:'Юнусабад, ул. Бунёдкор, 24а дом',
		src: "https://assets.thewanderinginvestor.com/wp-content/uploads/20200913005203/IMG_9808.jpg",
	},
	{
		id: 6,
		company_id: 6,
		title: "Golder House",
		comment: "Продается 2х комнатная квартирав Юнусабадском районе",
		toRailway: "4 мин до метро",
		space: "54.5",
		monthly: "2,000,000",
		address:'Юнусабад, ул. Бунёдкор, 24а дом',
		src: "https://i.ytimg.com/vi/o4clqyDFeAY/maxresdefault.jpg",
	},
	{
		id: 7,
		company_id: 7,
		title: "Namuna",
		comment: "Продается 2х комнатная квартирав Юнусабадском районе",
		toRailway: "4 мин до метро",
		space: "54.5",
		monthly: "3,400,000",
		address:'Юнусабад, ул. Бунёдкор, 24а дом',
		src: "https://assets.thewanderinginvestor.com/wp-content/uploads/20200913005203/IMG_9808.jpg",
	},
	{
		id: 8,
		company_id: 8,
		title: "Golder House",
		comment: "Продается 2х комнатная квартирав Юнусабадском районе",
		toRailway: "4 мин до метро",
		space: "54.5",
		monthly: "2,000,000",
		address:'Юнусабад, ул. Бунёдкор, 24а дом',
		src: "https://denverarchitecture.org/wp-content/uploads/2020/03/EquitableBuilding1.jpg",
	},
	{
		id: 9,
		company_id: 9,
		title: "Namuna",
		comment: "Продается 2х комнатная квартирав Юнусабадском районе",
		toRailway: "4 мин до метро",
		space: "54.5",
		monthly: "3,400,000",
		address:'Юнусабад, ул. Бунёдкор, 24а дом',
		src: "https://images.skyscrapercenter.com/building/tashkentcityzone2_rendering-1_(c)tashkent__city__ibc.jpg",
	},
	{
		id: 10,
		company_id: 10,
		title: "Namuna",
		comment: "Продается 2х комнатная квартирав Юнусабадском районе",
		toRailway: "4 мин до метро",
		space: "54.5",
		monthly: "3,400,000",
		address:'Юнусабад, ул. Бунёдкор, 24а дом',
		src: "https://denverarchitecture.org/wp-content/uploads/2020/03/EquitableBuilding1.jpg",
	},
];